#!/usr/bin/env bash
set -u

config_root=${XDG_CONFIG_HOME:-"$HOME/.config"}
status_file="$config_root/prettyzap/status.json"

sync_nbshell_palette() {
    local source_file="$config_root/nbshell/palette.sh"
    local target_dir="$config_root/prettyzap"
    local target_file="$target_dir/colors.toml"
    local temporary_file

    [[ -r "$source_file" ]] || return 0

    # palette.sh is generated by nbshell itself and resolves both supported
    # colors.toml dialects into one stable set of shell variables.
    # shellcheck source=/dev/null
    . "$source_file"

    mkdir -p "$target_dir"
    chmod 0700 "$target_dir"
    temporary_file=$(mktemp "$target_dir/colors.toml.XXXXXX") || return 0
    chmod 0600 "$temporary_file"
    {
        printf '# Generated from nbshell/palette.sh -- do not edit.\n'
        printf 'mode = "%s"\n\n' "$NB_MODE"
        printf 'background = "%s"\n' "$NB_BG"
        printf 'dark_background = "%s"\n' "$NB_BG_DARK"
        printf 'darker_background = "%s"\n' "$NB_BG_DARK"
        printf 'foreground = "%s"\n' "$NB_FG"
        printf 'muted = "%s"\n' "$NB_MUTED"
        printf 'accent = "%s"\n' "$NB_ACCENT"
        printf 'selection = "%s"\n' "$NB_SELECTION"
        printf 'red = "%s"\n' "$NB_RED"
        printf 'yellow = "%s"\n' "$NB_YELLOW"
        printf 'green = "%s"\n' "$NB_GREEN"
        printf 'blue = "%s"\n' "$NB_BLUE"
    } >"$temporary_file"

    if cmp -s "$temporary_file" "$target_file"; then
        rm -f "$temporary_file"
    else
        mv -f "$temporary_file" "$target_file"
    fi
}

sync_nbshell_palette

installed=false
command -v prettyzap >/dev/null 2>&1 && installed=true

if [[ -r "$status_file" ]] && jq -e 'type == "object"' "$status_file" >/dev/null 2>&1; then
    pid=$(jq -r '.pid // 0' "$status_file")
    running=false
    if [[ "$pid" =~ ^[0-9]+$ ]] && (( pid > 0 )) && kill -0 "$pid" 2>/dev/null; then
        running=true
    fi

    jq -c \
        --argjson installed "$installed" \
        --argjson running "$running" \
        '. + {
            installed: $installed,
            running: $running,
            visible: ($running and (.visible == true)),
            ready: ($running and (.ready == true)),
            unreadCount: ((.unreadCount // 0) | tonumber? // 0),
            notificationsEnabled: (.notificationsEnabled != false),
            theme: (if .theme == "system" then "system" else "whatsapp" end)
        }' "$status_file"
else
    jq -cn --argjson installed "$installed" '{
        installed: $installed,
        running: false,
        visible: false,
        ready: false,
        unreadCount: 0,
        notificationsEnabled: true,
        theme: "whatsapp"
    }'
fi
